package com.xc.dao;

import com.xc.model.AdminLog;

public interface AdminLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbggenerated
     */
    int insert(AdminLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbggenerated
     */
    int insertSelective(AdminLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbggenerated
     */
    AdminLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AdminLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdminLog record);
}