package com.xc.dao;

import com.xc.model.IdentificationLog;

public interface IdentificationLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_identification_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String originId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_identification_log
     *
     * @mbggenerated
     */
    int insert(IdentificationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_identification_log
     *
     * @mbggenerated
     */
    int insertSelective(IdentificationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_identification_log
     *
     * @mbggenerated
     */
    IdentificationLog selectByPrimaryKey(String originId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_identification_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IdentificationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_identification_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IdentificationLog record);
}