package com.xc.model;

import java.math.BigDecimal;
import java.util.Date;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_account.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_account.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_account.amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_account.frozen_amount
     *
     * @mbggenerated
     */
    private BigDecimal frozenAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_account.total_amount
     *
     * @mbggenerated
     */
    private BigDecimal totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_account.last_modified_time
     *
     * @mbggenerated
     */
    private Date lastModifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_account.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_account.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_account.id
     *
     * @return the value of uac_account.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_account.id
     *
     * @param id the value for uac_account.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_account.user_id
     *
     * @return the value of uac_account.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_account.user_id
     *
     * @param userId the value for uac_account.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_account.amount
     *
     * @return the value of uac_account.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_account.amount
     *
     * @param amount the value for uac_account.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_account.frozen_amount
     *
     * @return the value of uac_account.frozen_amount
     *
     * @mbggenerated
     */
    public BigDecimal getFrozenAmount() {
        return frozenAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_account.frozen_amount
     *
     * @param frozenAmount the value for uac_account.frozen_amount
     *
     * @mbggenerated
     */
    public void setFrozenAmount(BigDecimal frozenAmount) {
        this.frozenAmount = frozenAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_account.total_amount
     *
     * @return the value of uac_account.total_amount
     *
     * @mbggenerated
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_account.total_amount
     *
     * @param totalAmount the value for uac_account.total_amount
     *
     * @mbggenerated
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_account.last_modified_time
     *
     * @return the value of uac_account.last_modified_time
     *
     * @mbggenerated
     */
    public Date getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_account.last_modified_time
     *
     * @param lastModifiedTime the value for uac_account.last_modified_time
     *
     * @mbggenerated
     */
    public void setLastModifiedTime(Date lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_account.status
     *
     * @return the value of uac_account.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_account.status
     *
     * @param status the value for uac_account.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_account.version
     *
     * @return the value of uac_account.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_account.version
     *
     * @param version the value for uac_account.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}