package com.xc.model;

import java.math.BigDecimal;
import java.util.Date;

public class Coin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_coin.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_coin.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_coin.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_coin.coin
     *
     * @mbggenerated
     */
    private BigDecimal coin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_coin.frozen_coin
     *
     * @mbggenerated
     */
    private BigDecimal frozenCoin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_coin.total_coin
     *
     * @mbggenerated
     */
    private BigDecimal totalCoin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_coin.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_coin.last_modified_time
     *
     * @mbggenerated
     */
    private Date lastModifiedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_coin.id
     *
     * @return the value of uac_coin.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_coin.id
     *
     * @param id the value for uac_coin.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_coin.user_id
     *
     * @return the value of uac_coin.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_coin.user_id
     *
     * @param userId the value for uac_coin.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_coin.status
     *
     * @return the value of uac_coin.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_coin.status
     *
     * @param status the value for uac_coin.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_coin.coin
     *
     * @return the value of uac_coin.coin
     *
     * @mbggenerated
     */
    public BigDecimal getCoin() {
        return coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_coin.coin
     *
     * @param coin the value for uac_coin.coin
     *
     * @mbggenerated
     */
    public void setCoin(BigDecimal coin) {
        this.coin = coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_coin.frozen_coin
     *
     * @return the value of uac_coin.frozen_coin
     *
     * @mbggenerated
     */
    public BigDecimal getFrozenCoin() {
        return frozenCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_coin.frozen_coin
     *
     * @param frozenCoin the value for uac_coin.frozen_coin
     *
     * @mbggenerated
     */
    public void setFrozenCoin(BigDecimal frozenCoin) {
        this.frozenCoin = frozenCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_coin.total_coin
     *
     * @return the value of uac_coin.total_coin
     *
     * @mbggenerated
     */
    public BigDecimal getTotalCoin() {
        return totalCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_coin.total_coin
     *
     * @param totalCoin the value for uac_coin.total_coin
     *
     * @mbggenerated
     */
    public void setTotalCoin(BigDecimal totalCoin) {
        this.totalCoin = totalCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_coin.version
     *
     * @return the value of uac_coin.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_coin.version
     *
     * @param version the value for uac_coin.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_coin.last_modified_time
     *
     * @return the value of uac_coin.last_modified_time
     *
     * @mbggenerated
     */
    public Date getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_coin.last_modified_time
     *
     * @param lastModifiedTime the value for uac_coin.last_modified_time
     *
     * @mbggenerated
     */
    public void setLastModifiedTime(Date lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime;
    }
}