package com.xc.model;

import java.math.BigDecimal;

public class FastUserRepayDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_fast_user_repay_detail.subject_id
     *
     * @mbggenerated
     */
    private String subjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_fast_user_repay_detail.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_fast_user_repay_detail.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_fast_user_repay_detail.cust_id
     *
     * @mbggenerated
     */
    private Long custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_fast_user_repay_detail.cust_name
     *
     * @mbggenerated
     */
    private String custName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_fast_user_repay_detail.amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_fast_user_repay_detail.interest
     *
     * @mbggenerated
     */
    private BigDecimal interest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_fast_user_repay_detail.service_amount
     *
     * @mbggenerated
     */
    private BigDecimal serviceAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_fast_user_repay_detail.fixed_reward
     *
     * @mbggenerated
     */
    private BigDecimal fixedReward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_fast_user_repay_detail.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_fast_user_repay_detail.subject_id
     *
     * @return the value of tc_fast_user_repay_detail.subject_id
     *
     * @mbggenerated
     */
    public String getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_fast_user_repay_detail.subject_id
     *
     * @param subjectId the value for tc_fast_user_repay_detail.subject_id
     *
     * @mbggenerated
     */
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId == null ? null : subjectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_fast_user_repay_detail.user_id
     *
     * @return the value of tc_fast_user_repay_detail.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_fast_user_repay_detail.user_id
     *
     * @param userId the value for tc_fast_user_repay_detail.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_fast_user_repay_detail.user_name
     *
     * @return the value of tc_fast_user_repay_detail.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_fast_user_repay_detail.user_name
     *
     * @param userName the value for tc_fast_user_repay_detail.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_fast_user_repay_detail.cust_id
     *
     * @return the value of tc_fast_user_repay_detail.cust_id
     *
     * @mbggenerated
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_fast_user_repay_detail.cust_id
     *
     * @param custId the value for tc_fast_user_repay_detail.cust_id
     *
     * @mbggenerated
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_fast_user_repay_detail.cust_name
     *
     * @return the value of tc_fast_user_repay_detail.cust_name
     *
     * @mbggenerated
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_fast_user_repay_detail.cust_name
     *
     * @param custName the value for tc_fast_user_repay_detail.cust_name
     *
     * @mbggenerated
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_fast_user_repay_detail.amount
     *
     * @return the value of tc_fast_user_repay_detail.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_fast_user_repay_detail.amount
     *
     * @param amount the value for tc_fast_user_repay_detail.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_fast_user_repay_detail.interest
     *
     * @return the value of tc_fast_user_repay_detail.interest
     *
     * @mbggenerated
     */
    public BigDecimal getInterest() {
        return interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_fast_user_repay_detail.interest
     *
     * @param interest the value for tc_fast_user_repay_detail.interest
     *
     * @mbggenerated
     */
    public void setInterest(BigDecimal interest) {
        this.interest = interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_fast_user_repay_detail.service_amount
     *
     * @return the value of tc_fast_user_repay_detail.service_amount
     *
     * @mbggenerated
     */
    public BigDecimal getServiceAmount() {
        return serviceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_fast_user_repay_detail.service_amount
     *
     * @param serviceAmount the value for tc_fast_user_repay_detail.service_amount
     *
     * @mbggenerated
     */
    public void setServiceAmount(BigDecimal serviceAmount) {
        this.serviceAmount = serviceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_fast_user_repay_detail.fixed_reward
     *
     * @return the value of tc_fast_user_repay_detail.fixed_reward
     *
     * @mbggenerated
     */
    public BigDecimal getFixedReward() {
        return fixedReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_fast_user_repay_detail.fixed_reward
     *
     * @param fixedReward the value for tc_fast_user_repay_detail.fixed_reward
     *
     * @mbggenerated
     */
    public void setFixedReward(BigDecimal fixedReward) {
        this.fixedReward = fixedReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_fast_user_repay_detail.STATUS
     *
     * @return the value of tc_fast_user_repay_detail.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_fast_user_repay_detail.STATUS
     *
     * @param status the value for tc_fast_user_repay_detail.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}