package com.xc.model;

import java.math.BigDecimal;
import java.util.Date;

public class OverdueStatistics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_overdue_statistics.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_overdue_statistics.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_overdue_statistics.login_user_name
     *
     * @mbggenerated
     */
    private String loginUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_overdue_statistics.user_real_name
     *
     * @mbggenerated
     */
    private String userRealName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_overdue_statistics.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_overdue_statistics.amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_overdue_statistics.late_fee
     *
     * @mbggenerated
     */
    private BigDecimal lateFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_overdue_statistics.penalty
     *
     * @mbggenerated
     */
    private BigDecimal penalty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_overdue_statistics.plan_date
     *
     * @mbggenerated
     */
    private Date planDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_overdue_statistics.on_day_amount
     *
     * @mbggenerated
     */
    private BigDecimal onDayAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_overdue_statistics.limit_category
     *
     * @mbggenerated
     */
    private Integer limitCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_overdue_statistics.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_overdue_statistics.start_date
     *
     * @mbggenerated
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_overdue_statistics.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_overdue_statistics.id
     *
     * @return the value of tc_overdue_statistics.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_overdue_statistics.id
     *
     * @param id the value for tc_overdue_statistics.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_overdue_statistics.user_id
     *
     * @return the value of tc_overdue_statistics.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_overdue_statistics.user_id
     *
     * @param userId the value for tc_overdue_statistics.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_overdue_statistics.login_user_name
     *
     * @return the value of tc_overdue_statistics.login_user_name
     *
     * @mbggenerated
     */
    public String getLoginUserName() {
        return loginUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_overdue_statistics.login_user_name
     *
     * @param loginUserName the value for tc_overdue_statistics.login_user_name
     *
     * @mbggenerated
     */
    public void setLoginUserName(String loginUserName) {
        this.loginUserName = loginUserName == null ? null : loginUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_overdue_statistics.user_real_name
     *
     * @return the value of tc_overdue_statistics.user_real_name
     *
     * @mbggenerated
     */
    public String getUserRealName() {
        return userRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_overdue_statistics.user_real_name
     *
     * @param userRealName the value for tc_overdue_statistics.user_real_name
     *
     * @mbggenerated
     */
    public void setUserRealName(String userRealName) {
        this.userRealName = userRealName == null ? null : userRealName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_overdue_statistics.phone
     *
     * @return the value of tc_overdue_statistics.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_overdue_statistics.phone
     *
     * @param phone the value for tc_overdue_statistics.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_overdue_statistics.amount
     *
     * @return the value of tc_overdue_statistics.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_overdue_statistics.amount
     *
     * @param amount the value for tc_overdue_statistics.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_overdue_statistics.late_fee
     *
     * @return the value of tc_overdue_statistics.late_fee
     *
     * @mbggenerated
     */
    public BigDecimal getLateFee() {
        return lateFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_overdue_statistics.late_fee
     *
     * @param lateFee the value for tc_overdue_statistics.late_fee
     *
     * @mbggenerated
     */
    public void setLateFee(BigDecimal lateFee) {
        this.lateFee = lateFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_overdue_statistics.penalty
     *
     * @return the value of tc_overdue_statistics.penalty
     *
     * @mbggenerated
     */
    public BigDecimal getPenalty() {
        return penalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_overdue_statistics.penalty
     *
     * @param penalty the value for tc_overdue_statistics.penalty
     *
     * @mbggenerated
     */
    public void setPenalty(BigDecimal penalty) {
        this.penalty = penalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_overdue_statistics.plan_date
     *
     * @return the value of tc_overdue_statistics.plan_date
     *
     * @mbggenerated
     */
    public Date getPlanDate() {
        return planDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_overdue_statistics.plan_date
     *
     * @param planDate the value for tc_overdue_statistics.plan_date
     *
     * @mbggenerated
     */
    public void setPlanDate(Date planDate) {
        this.planDate = planDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_overdue_statistics.on_day_amount
     *
     * @return the value of tc_overdue_statistics.on_day_amount
     *
     * @mbggenerated
     */
    public BigDecimal getOnDayAmount() {
        return onDayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_overdue_statistics.on_day_amount
     *
     * @param onDayAmount the value for tc_overdue_statistics.on_day_amount
     *
     * @mbggenerated
     */
    public void setOnDayAmount(BigDecimal onDayAmount) {
        this.onDayAmount = onDayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_overdue_statistics.limit_category
     *
     * @return the value of tc_overdue_statistics.limit_category
     *
     * @mbggenerated
     */
    public Integer getLimitCategory() {
        return limitCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_overdue_statistics.limit_category
     *
     * @param limitCategory the value for tc_overdue_statistics.limit_category
     *
     * @mbggenerated
     */
    public void setLimitCategory(Integer limitCategory) {
        this.limitCategory = limitCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_overdue_statistics.create_date
     *
     * @return the value of tc_overdue_statistics.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_overdue_statistics.create_date
     *
     * @param createDate the value for tc_overdue_statistics.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_overdue_statistics.start_date
     *
     * @return the value of tc_overdue_statistics.start_date
     *
     * @mbggenerated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_overdue_statistics.start_date
     *
     * @param startDate the value for tc_overdue_statistics.start_date
     *
     * @mbggenerated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_overdue_statistics.status
     *
     * @return the value of tc_overdue_statistics.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_overdue_statistics.status
     *
     * @param status the value for tc_overdue_statistics.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}