package com.xc.model;

import java.util.Date;

public class Privilege {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.update_user_id
     *
     * @mbggenerated
     */
    private Long updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.loan_or
     *
     * @mbggenerated
     */
    private Integer loanOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.max_loan_term
     *
     * @mbggenerated
     */
    private Integer maxLoanTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.add_friend_or
     *
     * @mbggenerated
     */
    private Integer addFriendOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.bid_or
     *
     * @mbggenerated
     */
    private Integer bidOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.interior_or
     *
     * @mbggenerated
     */
    private Boolean interiorOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.withdrawal_or
     *
     * @mbggenerated
     */
    private Integer withdrawalOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.customer_service_or
     *
     * @mbggenerated
     */
    private Boolean customerServiceOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.technical_staff_or
     *
     * @mbggenerated
     */
    private Boolean technicalStaffOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.fast_user_or
     *
     * @mbggenerated
     */
    private Boolean fastUserOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.bound_bank_or
     *
     * @mbggenerated
     */
    private Boolean boundBankOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.identification_or
     *
     * @mbggenerated
     */
    private Boolean identificationOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.black_or
     *
     * @mbggenerated
     */
    private Boolean blackOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.hide_portrait_or
     *
     * @mbggenerated
     */
    private Boolean hidePortraitOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.day_payback_or
     *
     * @mbggenerated
     */
    private Integer dayPaybackOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.month_one_off_or
     *
     * @mbggenerated
     */
    private Integer monthOneOffOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.enable_borrowLimit_or
     *
     * @mbggenerated
     */
    private Byte enableBorrowlimitOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.limit_subject_day
     *
     * @mbggenerated
     */
    private Integer limitSubjectDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.auto_audit_or
     *
     * @mbggenerated
     */
    private Integer autoAuditOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.poundage_or
     *
     * @mbggenerated
     */
    private Integer poundageOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.auto_repayment_or
     *
     * @mbggenerated
     */
    private Integer autoRepaymentOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.auto_bid_or
     *
     * @mbggenerated
     */
    private Integer autoBidOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.offline_change_or
     *
     * @mbggenerated
     */
    private Integer offlineChangeOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.allow_appeal_or
     *
     * @mbggenerated
     */
    private Integer allowAppealOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.show_fastgroup_or
     *
     * @mbggenerated
     */
    private Integer showFastgroupOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.had_bidden_or
     *
     * @mbggenerated
     */
    private Boolean hadBiddenOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.subject_comment_or
     *
     * @mbggenerated
     */
    private Integer subjectCommentOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.send_msg_or
     *
     * @mbggenerated
     */
    private Integer sendMsgOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.view_friend_activity_or
     *
     * @mbggenerated
     */
    private Integer viewFriendActivityOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.had_bidden_fast_or
     *
     * @mbggenerated
     */
    private Boolean hadBiddenFastOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.login_or
     *
     * @mbggenerated
     */
    private Boolean loginOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.bind_login_qq
     *
     * @mbggenerated
     */
    private Integer bindLoginQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.allow_buyfast_or
     *
     * @mbggenerated
     */
    private Integer allowBuyfastOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.agreed_or
     *
     * @mbggenerated
     */
    private Boolean agreedOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.allow_transfer_fast_or
     *
     * @mbggenerated
     */
    private Integer allowTransferFastOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_privilege.withdrawal_large_or
     *
     * @mbggenerated
     */
    private Integer withdrawalLargeOr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.id
     *
     * @return the value of uc_privilege.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.id
     *
     * @param id the value for uc_privilege.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.user_id
     *
     * @return the value of uc_privilege.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.user_id
     *
     * @param userId the value for uc_privilege.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.create_time
     *
     * @return the value of uc_privilege.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.create_time
     *
     * @param createTime the value for uc_privilege.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.update_time
     *
     * @return the value of uc_privilege.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.update_time
     *
     * @param updateTime the value for uc_privilege.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.update_user_id
     *
     * @return the value of uc_privilege.update_user_id
     *
     * @mbggenerated
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.update_user_id
     *
     * @param updateUserId the value for uc_privilege.update_user_id
     *
     * @mbggenerated
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.loan_or
     *
     * @return the value of uc_privilege.loan_or
     *
     * @mbggenerated
     */
    public Integer getLoanOr() {
        return loanOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.loan_or
     *
     * @param loanOr the value for uc_privilege.loan_or
     *
     * @mbggenerated
     */
    public void setLoanOr(Integer loanOr) {
        this.loanOr = loanOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.max_loan_term
     *
     * @return the value of uc_privilege.max_loan_term
     *
     * @mbggenerated
     */
    public Integer getMaxLoanTerm() {
        return maxLoanTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.max_loan_term
     *
     * @param maxLoanTerm the value for uc_privilege.max_loan_term
     *
     * @mbggenerated
     */
    public void setMaxLoanTerm(Integer maxLoanTerm) {
        this.maxLoanTerm = maxLoanTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.add_friend_or
     *
     * @return the value of uc_privilege.add_friend_or
     *
     * @mbggenerated
     */
    public Integer getAddFriendOr() {
        return addFriendOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.add_friend_or
     *
     * @param addFriendOr the value for uc_privilege.add_friend_or
     *
     * @mbggenerated
     */
    public void setAddFriendOr(Integer addFriendOr) {
        this.addFriendOr = addFriendOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.bid_or
     *
     * @return the value of uc_privilege.bid_or
     *
     * @mbggenerated
     */
    public Integer getBidOr() {
        return bidOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.bid_or
     *
     * @param bidOr the value for uc_privilege.bid_or
     *
     * @mbggenerated
     */
    public void setBidOr(Integer bidOr) {
        this.bidOr = bidOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.interior_or
     *
     * @return the value of uc_privilege.interior_or
     *
     * @mbggenerated
     */
    public Boolean getInteriorOr() {
        return interiorOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.interior_or
     *
     * @param interiorOr the value for uc_privilege.interior_or
     *
     * @mbggenerated
     */
    public void setInteriorOr(Boolean interiorOr) {
        this.interiorOr = interiorOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.withdrawal_or
     *
     * @return the value of uc_privilege.withdrawal_or
     *
     * @mbggenerated
     */
    public Integer getWithdrawalOr() {
        return withdrawalOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.withdrawal_or
     *
     * @param withdrawalOr the value for uc_privilege.withdrawal_or
     *
     * @mbggenerated
     */
    public void setWithdrawalOr(Integer withdrawalOr) {
        this.withdrawalOr = withdrawalOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.customer_service_or
     *
     * @return the value of uc_privilege.customer_service_or
     *
     * @mbggenerated
     */
    public Boolean getCustomerServiceOr() {
        return customerServiceOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.customer_service_or
     *
     * @param customerServiceOr the value for uc_privilege.customer_service_or
     *
     * @mbggenerated
     */
    public void setCustomerServiceOr(Boolean customerServiceOr) {
        this.customerServiceOr = customerServiceOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.technical_staff_or
     *
     * @return the value of uc_privilege.technical_staff_or
     *
     * @mbggenerated
     */
    public Boolean getTechnicalStaffOr() {
        return technicalStaffOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.technical_staff_or
     *
     * @param technicalStaffOr the value for uc_privilege.technical_staff_or
     *
     * @mbggenerated
     */
    public void setTechnicalStaffOr(Boolean technicalStaffOr) {
        this.technicalStaffOr = technicalStaffOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.fast_user_or
     *
     * @return the value of uc_privilege.fast_user_or
     *
     * @mbggenerated
     */
    public Boolean getFastUserOr() {
        return fastUserOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.fast_user_or
     *
     * @param fastUserOr the value for uc_privilege.fast_user_or
     *
     * @mbggenerated
     */
    public void setFastUserOr(Boolean fastUserOr) {
        this.fastUserOr = fastUserOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.bound_bank_or
     *
     * @return the value of uc_privilege.bound_bank_or
     *
     * @mbggenerated
     */
    public Boolean getBoundBankOr() {
        return boundBankOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.bound_bank_or
     *
     * @param boundBankOr the value for uc_privilege.bound_bank_or
     *
     * @mbggenerated
     */
    public void setBoundBankOr(Boolean boundBankOr) {
        this.boundBankOr = boundBankOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.identification_or
     *
     * @return the value of uc_privilege.identification_or
     *
     * @mbggenerated
     */
    public Boolean getIdentificationOr() {
        return identificationOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.identification_or
     *
     * @param identificationOr the value for uc_privilege.identification_or
     *
     * @mbggenerated
     */
    public void setIdentificationOr(Boolean identificationOr) {
        this.identificationOr = identificationOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.black_or
     *
     * @return the value of uc_privilege.black_or
     *
     * @mbggenerated
     */
    public Boolean getBlackOr() {
        return blackOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.black_or
     *
     * @param blackOr the value for uc_privilege.black_or
     *
     * @mbggenerated
     */
    public void setBlackOr(Boolean blackOr) {
        this.blackOr = blackOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.hide_portrait_or
     *
     * @return the value of uc_privilege.hide_portrait_or
     *
     * @mbggenerated
     */
    public Boolean getHidePortraitOr() {
        return hidePortraitOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.hide_portrait_or
     *
     * @param hidePortraitOr the value for uc_privilege.hide_portrait_or
     *
     * @mbggenerated
     */
    public void setHidePortraitOr(Boolean hidePortraitOr) {
        this.hidePortraitOr = hidePortraitOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.day_payback_or
     *
     * @return the value of uc_privilege.day_payback_or
     *
     * @mbggenerated
     */
    public Integer getDayPaybackOr() {
        return dayPaybackOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.day_payback_or
     *
     * @param dayPaybackOr the value for uc_privilege.day_payback_or
     *
     * @mbggenerated
     */
    public void setDayPaybackOr(Integer dayPaybackOr) {
        this.dayPaybackOr = dayPaybackOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.month_one_off_or
     *
     * @return the value of uc_privilege.month_one_off_or
     *
     * @mbggenerated
     */
    public Integer getMonthOneOffOr() {
        return monthOneOffOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.month_one_off_or
     *
     * @param monthOneOffOr the value for uc_privilege.month_one_off_or
     *
     * @mbggenerated
     */
    public void setMonthOneOffOr(Integer monthOneOffOr) {
        this.monthOneOffOr = monthOneOffOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.enable_borrowLimit_or
     *
     * @return the value of uc_privilege.enable_borrowLimit_or
     *
     * @mbggenerated
     */
    public Byte getEnableBorrowlimitOr() {
        return enableBorrowlimitOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.enable_borrowLimit_or
     *
     * @param enableBorrowlimitOr the value for uc_privilege.enable_borrowLimit_or
     *
     * @mbggenerated
     */
    public void setEnableBorrowlimitOr(Byte enableBorrowlimitOr) {
        this.enableBorrowlimitOr = enableBorrowlimitOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.limit_subject_day
     *
     * @return the value of uc_privilege.limit_subject_day
     *
     * @mbggenerated
     */
    public Integer getLimitSubjectDay() {
        return limitSubjectDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.limit_subject_day
     *
     * @param limitSubjectDay the value for uc_privilege.limit_subject_day
     *
     * @mbggenerated
     */
    public void setLimitSubjectDay(Integer limitSubjectDay) {
        this.limitSubjectDay = limitSubjectDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.auto_audit_or
     *
     * @return the value of uc_privilege.auto_audit_or
     *
     * @mbggenerated
     */
    public Integer getAutoAuditOr() {
        return autoAuditOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.auto_audit_or
     *
     * @param autoAuditOr the value for uc_privilege.auto_audit_or
     *
     * @mbggenerated
     */
    public void setAutoAuditOr(Integer autoAuditOr) {
        this.autoAuditOr = autoAuditOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.poundage_or
     *
     * @return the value of uc_privilege.poundage_or
     *
     * @mbggenerated
     */
    public Integer getPoundageOr() {
        return poundageOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.poundage_or
     *
     * @param poundageOr the value for uc_privilege.poundage_or
     *
     * @mbggenerated
     */
    public void setPoundageOr(Integer poundageOr) {
        this.poundageOr = poundageOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.auto_repayment_or
     *
     * @return the value of uc_privilege.auto_repayment_or
     *
     * @mbggenerated
     */
    public Integer getAutoRepaymentOr() {
        return autoRepaymentOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.auto_repayment_or
     *
     * @param autoRepaymentOr the value for uc_privilege.auto_repayment_or
     *
     * @mbggenerated
     */
    public void setAutoRepaymentOr(Integer autoRepaymentOr) {
        this.autoRepaymentOr = autoRepaymentOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.auto_bid_or
     *
     * @return the value of uc_privilege.auto_bid_or
     *
     * @mbggenerated
     */
    public Integer getAutoBidOr() {
        return autoBidOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.auto_bid_or
     *
     * @param autoBidOr the value for uc_privilege.auto_bid_or
     *
     * @mbggenerated
     */
    public void setAutoBidOr(Integer autoBidOr) {
        this.autoBidOr = autoBidOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.offline_change_or
     *
     * @return the value of uc_privilege.offline_change_or
     *
     * @mbggenerated
     */
    public Integer getOfflineChangeOr() {
        return offlineChangeOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.offline_change_or
     *
     * @param offlineChangeOr the value for uc_privilege.offline_change_or
     *
     * @mbggenerated
     */
    public void setOfflineChangeOr(Integer offlineChangeOr) {
        this.offlineChangeOr = offlineChangeOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.allow_appeal_or
     *
     * @return the value of uc_privilege.allow_appeal_or
     *
     * @mbggenerated
     */
    public Integer getAllowAppealOr() {
        return allowAppealOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.allow_appeal_or
     *
     * @param allowAppealOr the value for uc_privilege.allow_appeal_or
     *
     * @mbggenerated
     */
    public void setAllowAppealOr(Integer allowAppealOr) {
        this.allowAppealOr = allowAppealOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.show_fastgroup_or
     *
     * @return the value of uc_privilege.show_fastgroup_or
     *
     * @mbggenerated
     */
    public Integer getShowFastgroupOr() {
        return showFastgroupOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.show_fastgroup_or
     *
     * @param showFastgroupOr the value for uc_privilege.show_fastgroup_or
     *
     * @mbggenerated
     */
    public void setShowFastgroupOr(Integer showFastgroupOr) {
        this.showFastgroupOr = showFastgroupOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.had_bidden_or
     *
     * @return the value of uc_privilege.had_bidden_or
     *
     * @mbggenerated
     */
    public Boolean getHadBiddenOr() {
        return hadBiddenOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.had_bidden_or
     *
     * @param hadBiddenOr the value for uc_privilege.had_bidden_or
     *
     * @mbggenerated
     */
    public void setHadBiddenOr(Boolean hadBiddenOr) {
        this.hadBiddenOr = hadBiddenOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.subject_comment_or
     *
     * @return the value of uc_privilege.subject_comment_or
     *
     * @mbggenerated
     */
    public Integer getSubjectCommentOr() {
        return subjectCommentOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.subject_comment_or
     *
     * @param subjectCommentOr the value for uc_privilege.subject_comment_or
     *
     * @mbggenerated
     */
    public void setSubjectCommentOr(Integer subjectCommentOr) {
        this.subjectCommentOr = subjectCommentOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.send_msg_or
     *
     * @return the value of uc_privilege.send_msg_or
     *
     * @mbggenerated
     */
    public Integer getSendMsgOr() {
        return sendMsgOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.send_msg_or
     *
     * @param sendMsgOr the value for uc_privilege.send_msg_or
     *
     * @mbggenerated
     */
    public void setSendMsgOr(Integer sendMsgOr) {
        this.sendMsgOr = sendMsgOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.view_friend_activity_or
     *
     * @return the value of uc_privilege.view_friend_activity_or
     *
     * @mbggenerated
     */
    public Integer getViewFriendActivityOr() {
        return viewFriendActivityOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.view_friend_activity_or
     *
     * @param viewFriendActivityOr the value for uc_privilege.view_friend_activity_or
     *
     * @mbggenerated
     */
    public void setViewFriendActivityOr(Integer viewFriendActivityOr) {
        this.viewFriendActivityOr = viewFriendActivityOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.had_bidden_fast_or
     *
     * @return the value of uc_privilege.had_bidden_fast_or
     *
     * @mbggenerated
     */
    public Boolean getHadBiddenFastOr() {
        return hadBiddenFastOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.had_bidden_fast_or
     *
     * @param hadBiddenFastOr the value for uc_privilege.had_bidden_fast_or
     *
     * @mbggenerated
     */
    public void setHadBiddenFastOr(Boolean hadBiddenFastOr) {
        this.hadBiddenFastOr = hadBiddenFastOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.login_or
     *
     * @return the value of uc_privilege.login_or
     *
     * @mbggenerated
     */
    public Boolean getLoginOr() {
        return loginOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.login_or
     *
     * @param loginOr the value for uc_privilege.login_or
     *
     * @mbggenerated
     */
    public void setLoginOr(Boolean loginOr) {
        this.loginOr = loginOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.bind_login_qq
     *
     * @return the value of uc_privilege.bind_login_qq
     *
     * @mbggenerated
     */
    public Integer getBindLoginQq() {
        return bindLoginQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.bind_login_qq
     *
     * @param bindLoginQq the value for uc_privilege.bind_login_qq
     *
     * @mbggenerated
     */
    public void setBindLoginQq(Integer bindLoginQq) {
        this.bindLoginQq = bindLoginQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.allow_buyfast_or
     *
     * @return the value of uc_privilege.allow_buyfast_or
     *
     * @mbggenerated
     */
    public Integer getAllowBuyfastOr() {
        return allowBuyfastOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.allow_buyfast_or
     *
     * @param allowBuyfastOr the value for uc_privilege.allow_buyfast_or
     *
     * @mbggenerated
     */
    public void setAllowBuyfastOr(Integer allowBuyfastOr) {
        this.allowBuyfastOr = allowBuyfastOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.agreed_or
     *
     * @return the value of uc_privilege.agreed_or
     *
     * @mbggenerated
     */
    public Boolean getAgreedOr() {
        return agreedOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.agreed_or
     *
     * @param agreedOr the value for uc_privilege.agreed_or
     *
     * @mbggenerated
     */
    public void setAgreedOr(Boolean agreedOr) {
        this.agreedOr = agreedOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.allow_transfer_fast_or
     *
     * @return the value of uc_privilege.allow_transfer_fast_or
     *
     * @mbggenerated
     */
    public Integer getAllowTransferFastOr() {
        return allowTransferFastOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.allow_transfer_fast_or
     *
     * @param allowTransferFastOr the value for uc_privilege.allow_transfer_fast_or
     *
     * @mbggenerated
     */
    public void setAllowTransferFastOr(Integer allowTransferFastOr) {
        this.allowTransferFastOr = allowTransferFastOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_privilege.withdrawal_large_or
     *
     * @return the value of uc_privilege.withdrawal_large_or
     *
     * @mbggenerated
     */
    public Integer getWithdrawalLargeOr() {
        return withdrawalLargeOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_privilege.withdrawal_large_or
     *
     * @param withdrawalLargeOr the value for uc_privilege.withdrawal_large_or
     *
     * @mbggenerated
     */
    public void setWithdrawalLargeOr(Integer withdrawalLargeOr) {
        this.withdrawalLargeOr = withdrawalLargeOr;
    }
}