package com.xc.model;

import java.math.BigDecimal;

public class Score {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_score.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_score.score_amount
     *
     * @mbggenerated
     */
    private BigDecimal scoreAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_score.total_score
     *
     * @mbggenerated
     */
    private BigDecimal totalScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_score.frozen_score
     *
     * @mbggenerated
     */
    private BigDecimal frozenScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_score.consumed_score
     *
     * @mbggenerated
     */
    private BigDecimal consumedScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_score.score_level
     *
     * @mbggenerated
     */
    private Integer scoreLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_score.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_score.vouch_score
     *
     * @mbggenerated
     */
    private BigDecimal vouchScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_score.exchangable_score
     *
     * @mbggenerated
     */
    private BigDecimal exchangableScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_score.loan_score
     *
     * @mbggenerated
     */
    private BigDecimal loanScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_score.bid_score
     *
     * @mbggenerated
     */
    private BigDecimal bidScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uac_score.loan_all_repay_score
     *
     * @mbggenerated
     */
    private BigDecimal loanAllRepayScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_score.user_id
     *
     * @return the value of uac_score.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_score.user_id
     *
     * @param userId the value for uac_score.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_score.score_amount
     *
     * @return the value of uac_score.score_amount
     *
     * @mbggenerated
     */
    public BigDecimal getScoreAmount() {
        return scoreAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_score.score_amount
     *
     * @param scoreAmount the value for uac_score.score_amount
     *
     * @mbggenerated
     */
    public void setScoreAmount(BigDecimal scoreAmount) {
        this.scoreAmount = scoreAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_score.total_score
     *
     * @return the value of uac_score.total_score
     *
     * @mbggenerated
     */
    public BigDecimal getTotalScore() {
        return totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_score.total_score
     *
     * @param totalScore the value for uac_score.total_score
     *
     * @mbggenerated
     */
    public void setTotalScore(BigDecimal totalScore) {
        this.totalScore = totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_score.frozen_score
     *
     * @return the value of uac_score.frozen_score
     *
     * @mbggenerated
     */
    public BigDecimal getFrozenScore() {
        return frozenScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_score.frozen_score
     *
     * @param frozenScore the value for uac_score.frozen_score
     *
     * @mbggenerated
     */
    public void setFrozenScore(BigDecimal frozenScore) {
        this.frozenScore = frozenScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_score.consumed_score
     *
     * @return the value of uac_score.consumed_score
     *
     * @mbggenerated
     */
    public BigDecimal getConsumedScore() {
        return consumedScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_score.consumed_score
     *
     * @param consumedScore the value for uac_score.consumed_score
     *
     * @mbggenerated
     */
    public void setConsumedScore(BigDecimal consumedScore) {
        this.consumedScore = consumedScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_score.score_level
     *
     * @return the value of uac_score.score_level
     *
     * @mbggenerated
     */
    public Integer getScoreLevel() {
        return scoreLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_score.score_level
     *
     * @param scoreLevel the value for uac_score.score_level
     *
     * @mbggenerated
     */
    public void setScoreLevel(Integer scoreLevel) {
        this.scoreLevel = scoreLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_score.version
     *
     * @return the value of uac_score.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_score.version
     *
     * @param version the value for uac_score.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_score.vouch_score
     *
     * @return the value of uac_score.vouch_score
     *
     * @mbggenerated
     */
    public BigDecimal getVouchScore() {
        return vouchScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_score.vouch_score
     *
     * @param vouchScore the value for uac_score.vouch_score
     *
     * @mbggenerated
     */
    public void setVouchScore(BigDecimal vouchScore) {
        this.vouchScore = vouchScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_score.exchangable_score
     *
     * @return the value of uac_score.exchangable_score
     *
     * @mbggenerated
     */
    public BigDecimal getExchangableScore() {
        return exchangableScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_score.exchangable_score
     *
     * @param exchangableScore the value for uac_score.exchangable_score
     *
     * @mbggenerated
     */
    public void setExchangableScore(BigDecimal exchangableScore) {
        this.exchangableScore = exchangableScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_score.loan_score
     *
     * @return the value of uac_score.loan_score
     *
     * @mbggenerated
     */
    public BigDecimal getLoanScore() {
        return loanScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_score.loan_score
     *
     * @param loanScore the value for uac_score.loan_score
     *
     * @mbggenerated
     */
    public void setLoanScore(BigDecimal loanScore) {
        this.loanScore = loanScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_score.bid_score
     *
     * @return the value of uac_score.bid_score
     *
     * @mbggenerated
     */
    public BigDecimal getBidScore() {
        return bidScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_score.bid_score
     *
     * @param bidScore the value for uac_score.bid_score
     *
     * @mbggenerated
     */
    public void setBidScore(BigDecimal bidScore) {
        this.bidScore = bidScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uac_score.loan_all_repay_score
     *
     * @return the value of uac_score.loan_all_repay_score
     *
     * @mbggenerated
     */
    public BigDecimal getLoanAllRepayScore() {
        return loanAllRepayScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uac_score.loan_all_repay_score
     *
     * @param loanAllRepayScore the value for uac_score.loan_all_repay_score
     *
     * @mbggenerated
     */
    public void setLoanAllRepayScore(BigDecimal loanAllRepayScore) {
        this.loanAllRepayScore = loanAllRepayScore;
    }
}