package com.xc.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.login_username
     *
     * @mbggenerated
     */
    private String loginUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.transaction_password
     *
     * @mbggenerated
     */
    private String transactionPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.portrait
     *
     * @mbggenerated
     */
    private String portrait;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.registered_time
     *
     * @mbggenerated
     */
    private Date registeredTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.expiration_date
     *
     * @mbggenerated
     */
    private Date expirationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.last_login_time
     *
     * @mbggenerated
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.origin_category
     *
     * @mbggenerated
     */
    private Integer originCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.vip_type
     *
     * @mbggenerated
     */
    private Integer vipType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.bound_cellphone
     *
     * @mbggenerated
     */
    private String boundCellphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.bound_email
     *
     * @mbggenerated
     */
    private String boundEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.customer_service_id
     *
     * @mbggenerated
     */
    private Long customerServiceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.speread_code
     *
     * @mbggenerated
     */
    private String spereadCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.signature
     *
     * @mbggenerated
     */
    private String signature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.vip_start_date
     *
     * @mbggenerated
     */
    private Date vipStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.vip_end_date
     *
     * @mbggenerated
     */
    private Date vipEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.vip_status
     *
     * @mbggenerated
     */
    private Integer vipStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.active_or
     *
     * @mbggenerated
     */
    private Boolean activeOr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.guide_user_id
     *
     * @mbggenerated
     */
    private Long guideUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.guide_status
     *
     * @mbggenerated
     */
    private Integer guideStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.frist_guide_time
     *
     * @mbggenerated
     */
    private Date fristGuideTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.last_guide_time
     *
     * @mbggenerated
     */
    private Date lastGuideTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.track_level
     *
     * @mbggenerated
     */
    private Integer trackLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user.boitice_bid_or
     *
     * @mbggenerated
     */
    private Boolean boiticeBidOr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.id
     *
     * @return the value of uc_user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.id
     *
     * @param id the value for uc_user.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.login_username
     *
     * @return the value of uc_user.login_username
     *
     * @mbggenerated
     */
    public String getLoginUsername() {
        return loginUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.login_username
     *
     * @param loginUsername the value for uc_user.login_username
     *
     * @mbggenerated
     */
    public void setLoginUsername(String loginUsername) {
        this.loginUsername = loginUsername == null ? null : loginUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.nickname
     *
     * @return the value of uc_user.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.nickname
     *
     * @param nickname the value for uc_user.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.password
     *
     * @return the value of uc_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.password
     *
     * @param password the value for uc_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.transaction_password
     *
     * @return the value of uc_user.transaction_password
     *
     * @mbggenerated
     */
    public String getTransactionPassword() {
        return transactionPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.transaction_password
     *
     * @param transactionPassword the value for uc_user.transaction_password
     *
     * @mbggenerated
     */
    public void setTransactionPassword(String transactionPassword) {
        this.transactionPassword = transactionPassword == null ? null : transactionPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.portrait
     *
     * @return the value of uc_user.portrait
     *
     * @mbggenerated
     */
    public String getPortrait() {
        return portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.portrait
     *
     * @param portrait the value for uc_user.portrait
     *
     * @mbggenerated
     */
    public void setPortrait(String portrait) {
        this.portrait = portrait == null ? null : portrait.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.registered_time
     *
     * @return the value of uc_user.registered_time
     *
     * @mbggenerated
     */
    public Date getRegisteredTime() {
        return registeredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.registered_time
     *
     * @param registeredTime the value for uc_user.registered_time
     *
     * @mbggenerated
     */
    public void setRegisteredTime(Date registeredTime) {
        this.registeredTime = registeredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.expiration_date
     *
     * @return the value of uc_user.expiration_date
     *
     * @mbggenerated
     */
    public Date getExpirationDate() {
        return expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.expiration_date
     *
     * @param expirationDate the value for uc_user.expiration_date
     *
     * @mbggenerated
     */
    public void setExpirationDate(Date expirationDate) {
        this.expirationDate = expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.last_login_time
     *
     * @return the value of uc_user.last_login_time
     *
     * @mbggenerated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.last_login_time
     *
     * @param lastLoginTime the value for uc_user.last_login_time
     *
     * @mbggenerated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.type
     *
     * @return the value of uc_user.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.type
     *
     * @param type the value for uc_user.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.origin_category
     *
     * @return the value of uc_user.origin_category
     *
     * @mbggenerated
     */
    public Integer getOriginCategory() {
        return originCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.origin_category
     *
     * @param originCategory the value for uc_user.origin_category
     *
     * @mbggenerated
     */
    public void setOriginCategory(Integer originCategory) {
        this.originCategory = originCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.status
     *
     * @return the value of uc_user.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.status
     *
     * @param status the value for uc_user.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.vip_type
     *
     * @return the value of uc_user.vip_type
     *
     * @mbggenerated
     */
    public Integer getVipType() {
        return vipType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.vip_type
     *
     * @param vipType the value for uc_user.vip_type
     *
     * @mbggenerated
     */
    public void setVipType(Integer vipType) {
        this.vipType = vipType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.level
     *
     * @return the value of uc_user.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.level
     *
     * @param level the value for uc_user.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.bound_cellphone
     *
     * @return the value of uc_user.bound_cellphone
     *
     * @mbggenerated
     */
    public String getBoundCellphone() {
        return boundCellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.bound_cellphone
     *
     * @param boundCellphone the value for uc_user.bound_cellphone
     *
     * @mbggenerated
     */
    public void setBoundCellphone(String boundCellphone) {
        this.boundCellphone = boundCellphone == null ? null : boundCellphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.bound_email
     *
     * @return the value of uc_user.bound_email
     *
     * @mbggenerated
     */
    public String getBoundEmail() {
        return boundEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.bound_email
     *
     * @param boundEmail the value for uc_user.bound_email
     *
     * @mbggenerated
     */
    public void setBoundEmail(String boundEmail) {
        this.boundEmail = boundEmail == null ? null : boundEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.uid
     *
     * @return the value of uc_user.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.uid
     *
     * @param uid the value for uc_user.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.customer_service_id
     *
     * @return the value of uc_user.customer_service_id
     *
     * @mbggenerated
     */
    public Long getCustomerServiceId() {
        return customerServiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.customer_service_id
     *
     * @param customerServiceId the value for uc_user.customer_service_id
     *
     * @mbggenerated
     */
    public void setCustomerServiceId(Long customerServiceId) {
        this.customerServiceId = customerServiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.speread_code
     *
     * @return the value of uc_user.speread_code
     *
     * @mbggenerated
     */
    public String getSpereadCode() {
        return spereadCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.speread_code
     *
     * @param spereadCode the value for uc_user.speread_code
     *
     * @mbggenerated
     */
    public void setSpereadCode(String spereadCode) {
        this.spereadCode = spereadCode == null ? null : spereadCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.signature
     *
     * @return the value of uc_user.signature
     *
     * @mbggenerated
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.signature
     *
     * @param signature the value for uc_user.signature
     *
     * @mbggenerated
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.vip_start_date
     *
     * @return the value of uc_user.vip_start_date
     *
     * @mbggenerated
     */
    public Date getVipStartDate() {
        return vipStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.vip_start_date
     *
     * @param vipStartDate the value for uc_user.vip_start_date
     *
     * @mbggenerated
     */
    public void setVipStartDate(Date vipStartDate) {
        this.vipStartDate = vipStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.vip_end_date
     *
     * @return the value of uc_user.vip_end_date
     *
     * @mbggenerated
     */
    public Date getVipEndDate() {
        return vipEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.vip_end_date
     *
     * @param vipEndDate the value for uc_user.vip_end_date
     *
     * @mbggenerated
     */
    public void setVipEndDate(Date vipEndDate) {
        this.vipEndDate = vipEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.vip_status
     *
     * @return the value of uc_user.vip_status
     *
     * @mbggenerated
     */
    public Integer getVipStatus() {
        return vipStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.vip_status
     *
     * @param vipStatus the value for uc_user.vip_status
     *
     * @mbggenerated
     */
    public void setVipStatus(Integer vipStatus) {
        this.vipStatus = vipStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.active_or
     *
     * @return the value of uc_user.active_or
     *
     * @mbggenerated
     */
    public Boolean getActiveOr() {
        return activeOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.active_or
     *
     * @param activeOr the value for uc_user.active_or
     *
     * @mbggenerated
     */
    public void setActiveOr(Boolean activeOr) {
        this.activeOr = activeOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.guide_user_id
     *
     * @return the value of uc_user.guide_user_id
     *
     * @mbggenerated
     */
    public Long getGuideUserId() {
        return guideUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.guide_user_id
     *
     * @param guideUserId the value for uc_user.guide_user_id
     *
     * @mbggenerated
     */
    public void setGuideUserId(Long guideUserId) {
        this.guideUserId = guideUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.guide_status
     *
     * @return the value of uc_user.guide_status
     *
     * @mbggenerated
     */
    public Integer getGuideStatus() {
        return guideStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.guide_status
     *
     * @param guideStatus the value for uc_user.guide_status
     *
     * @mbggenerated
     */
    public void setGuideStatus(Integer guideStatus) {
        this.guideStatus = guideStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.frist_guide_time
     *
     * @return the value of uc_user.frist_guide_time
     *
     * @mbggenerated
     */
    public Date getFristGuideTime() {
        return fristGuideTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.frist_guide_time
     *
     * @param fristGuideTime the value for uc_user.frist_guide_time
     *
     * @mbggenerated
     */
    public void setFristGuideTime(Date fristGuideTime) {
        this.fristGuideTime = fristGuideTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.last_guide_time
     *
     * @return the value of uc_user.last_guide_time
     *
     * @mbggenerated
     */
    public Date getLastGuideTime() {
        return lastGuideTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.last_guide_time
     *
     * @param lastGuideTime the value for uc_user.last_guide_time
     *
     * @mbggenerated
     */
    public void setLastGuideTime(Date lastGuideTime) {
        this.lastGuideTime = lastGuideTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.track_level
     *
     * @return the value of uc_user.track_level
     *
     * @mbggenerated
     */
    public Integer getTrackLevel() {
        return trackLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.track_level
     *
     * @param trackLevel the value for uc_user.track_level
     *
     * @mbggenerated
     */
    public void setTrackLevel(Integer trackLevel) {
        this.trackLevel = trackLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user.boitice_bid_or
     *
     * @return the value of uc_user.boitice_bid_or
     *
     * @mbggenerated
     */
    public Boolean getBoiticeBidOr() {
        return boiticeBidOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user.boitice_bid_or
     *
     * @param boiticeBidOr the value for uc_user.boitice_bid_or
     *
     * @mbggenerated
     */
    public void setBoiticeBidOr(Boolean boiticeBidOr) {
        this.boiticeBidOr = boiticeBidOr;
    }
}